"""Rebuild the mermaid skill, README and notices from the bundled references."""

from __future__ import annotations

import errno
import json
import os
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from plugin_maintenance.paths import REPO_ROOT

PLUGIN_NAME = "mermaid-diagrams"
PLUGIN_ROOT = REPO_ROOT / "plugins" / PLUGIN_NAME
REFERENCES_DIR = PLUGIN_ROOT / "skills/mermaid/references"
MERMAID_SKILL_PATH = PLUGIN_ROOT / "skills/mermaid/SKILL.md"
README_PATH = PLUGIN_ROOT / "README.md"
THIRD_PARTY_NOTICES_PATH = PLUGIN_ROOT / "THIRD_PARTY_NOTICES.md"
TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
MERMAID_SKILL_TEMPLATE_PATH = TEMPLATES_DIR / "mermaid_skill.md"
README_TEMPLATE_PATH = TEMPLATES_DIR / "readme.md"
BUNDLED_DOCS_NAVIGATION_PATH = Path(__file__).resolve().parent / "mermaid_navigation.json"
DEFAULT_DOCS_NAVIGATION_PATH = PLUGIN_ROOT / "mermaid-source/packages/mermaid/src/docs/.vitepress/config.ts"
SUMMARY_LIMIT = 220
MAX_SAFE_INTEGER = 9_007_199_254_740_991

GENERATED_HEADER_PATTERN = re.compile(
    r"^> \*\*Warning\*\*\n>\n"
    r"> ## THIS IS AN AUTOGENERATED FILE\. DO NOT EDIT\.\n>\n"
    r"> ## Please edit the corresponding file in \[[^\]]+\]\([^)]+\)\.\n\n"
)
SYNC_STATUS_PATTERN = re.compile(
    r"<!-- BEGIN GENERATED SYNC STATUS -->\n"
    r"(?P<status>[\s\S]*?)\n"
    r"<!-- END GENERATED SYNC STATUS -->"
)


@dataclass(frozen=True)
class DiagramMetadata:
    """One syntax reference as listed in the skill's diagram table."""

    id: str
    file: str
    title: str
    use_cases: str
    category: str
    order: int


@dataclass(frozen=True)
class NavigationMetadata:
    """Sidebar category, order and title of one diagram in the Mermaid docs."""

    category: str
    order: int
    title: str


@dataclass(frozen=True)
class SyncMetadata:
    """Source, commit and date of the last upstream docs sync."""

    source: str
    commit: str
    date: str


def plugin_relative_path(path: str | Path) -> Path:
    """Resolve `path` against the plugin root unless it is already absolute."""
    candidate = Path(path)
    if candidate.is_absolute():
        return candidate
    return PLUGIN_ROOT / candidate


def js_iso_timestamp() -> str:
    """Return the current UTC time as JavaScript's `toISOString()` writes it."""
    now = datetime.now(UTC)
    milliseconds = now.microsecond // 1000
    return f"{now:%Y-%m-%dT%H:%M:%S}.{milliseconds:03d}Z"


def title_from_id(identifier: str) -> str:
    """Turn a file identifier such as `sequenceDiagram` into a title."""
    title = re.sub(r"([a-z])([A-Z])", r"\1 \2", identifier)
    title = title.replace("-", " ").replace("_", " ")
    return re.sub(r"\b\w", lambda match: match.group(0).upper(), title)


def normalize_markdown_text(text: str, *, escape_table_pipes: bool = False) -> str:
    """Strip links, code spans and emphasis, collapse whitespace, and optionally escape `|`."""
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\*\*([^*]*)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]*)\*", r"\1", text)
    text = re.sub(r"<[^>]+>", "", text)
    normalized = re.sub(r"\s+", " ", text).strip()
    if escape_table_pipes:
        return normalized.replace("|", r"\|")
    return normalized


def clean_sidebar_text(text: str) -> str:
    """Normalize a sidebar label to plain printable ASCII."""
    text = normalize_markdown_text(text)
    text = re.sub(r"[^\x20-\x7E]", "", text)
    return re.sub(r"\s+", " ", text).strip()


def clean_title(text: str) -> str:
    """Normalize a heading and drop its version badge."""
    text = normalize_markdown_text(text, escape_table_pipes=True)
    text = re.sub(r"\s*\(v\\?<[^\)]*\)", "", text)
    text = re.sub(r"\s*\(v\\?\+\)", "", text)
    return text.strip()


def first_heading(text: str) -> str | None:
    """Return the cleaned text of the first level-1 heading, or None."""
    match = re.search(r"^#\s+(.+)$", text, flags=re.MULTILINE)
    if not match:
        return None
    return clean_title(match.group(1))


def first_useful_paragraph(text: str) -> str:
    """Summarize a reference by its first prose paragraph after the title."""
    lines = re.split(r"\r?\n", text)
    first_heading_index = next(
        (index for index, line in enumerate(lines) if re.match(r"^#\s+", line)),
        -1,
    )
    body_lines = lines if first_heading_index == -1 else lines[first_heading_index + 1 :]
    paragraph: list[str] = []
    in_fence = False
    skipping_admonition = False

    for raw_line in body_lines:
        trimmed = raw_line.strip()

        if re.search(r"^```|^:::", trimmed):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if not trimmed:
            if paragraph:
                break
            skipping_admonition = False
            continue
        if re.search(r"^#{1,6}\s+", trimmed):
            continue
        if re.search(r"^>\s*\*\*(Warning|Note|Deprecated)\*\*", trimmed, re.IGNORECASE):
            skipping_admonition = True
            continue
        if skipping_admonition and trimmed.startswith(">"):
            continue
        if not paragraph and (
            re.search(r"^\|", trimmed) or re.search(r"^[-*]\s+", trimmed) or re.search(r"^!\[", trimmed)
        ):
            continue

        paragraph.append(re.sub(r"^>\s?", "", trimmed, count=1))

    return shorten_summary(normalize_markdown_text(" ".join(paragraph), escape_table_pipes=True))


def shorten_summary(summary: str) -> str:
    """Cut a summary to its first sentence, or to `SUMMARY_LIMIT` characters."""
    if not summary:
        return "See reference documentation."
    first_sentence = re.match(rf"^.{{1,{SUMMARY_LIMIT}}}?[.!?](?=\s|$)", summary)
    if first_sentence:
        return first_sentence.group(0)
    if len(summary) > SUMMARY_LIMIT:
        return f"{summary[: SUMMARY_LIMIT - 3].strip()}..."
    return summary


def function_block(text: str, function_name: str) -> str:
    """Return the body of the JavaScript function `function_name`, or an empty string."""
    start = text.find(f"function {function_name}()")
    if start == -1:
        return ""

    open_brace = text.find("{", start)
    if open_brace == -1:
        return ""

    depth = 0
    for index in range(open_brace, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace + 1 : index]

    return ""


def parse_navigation_config(config: str) -> dict[str, NavigationMetadata]:
    """Read diagram navigation metadata from the Mermaid docs sidebar config."""
    syntax_block = function_block(config, "sidebarSyntax")
    metadata: dict[str, NavigationMetadata] = {}
    section_pattern = re.compile(
        r"\{\s*text:\s*['\"`]([^'\"`]+)['\"`][\s\S]*?"
        r"items:\s*\[([\s\S]*?)\]\s*,?\s*\}"
    )
    item_pattern = re.compile(
        r"\{\s*text:\s*['\"`]([^'\"`]+)['\"`]\s*,\s*"
        r"link:\s*['\"`]\/syntax\/([^'\"`#]+)(?:#[^'\"`]*)?['\"`]\s*\}"
    )
    order = 0

    for section_match in section_pattern.finditer(syntax_block):
        category = clean_sidebar_text(section_match.group(1)) or "Diagram Syntax"
        items = section_match.group(2)

        for item_match in item_pattern.finditer(items):
            title = clean_sidebar_text(item_match.group(1))
            identifier = item_match.group(2)
            metadata[identifier] = NavigationMetadata(
                category=category,
                order=order,
                title=clean_title(title or title_from_id(identifier)),
            )
            order += 1

    return metadata


def navigation_metadata_from_entries(
    entries: list[dict[str, Any]],
) -> dict[str, NavigationMetadata]:
    """Build navigation metadata from its bundled JSON entries."""
    metadata: dict[str, NavigationMetadata] = {}

    for entry in entries:
        identifier = str(entry["id"])
        metadata[identifier] = NavigationMetadata(
            category=normalize_markdown_text(
                str(entry.get("category") or "Diagram Syntax"),
                escape_table_pipes=True,
            ),
            order=int(entry["order"]),
            title=clean_title(str(entry.get("title") or title_from_id(identifier))),
        )

    return metadata


def navigation_metadata_entries(
    metadata: dict[str, NavigationMetadata],
) -> list[dict[str, object]]:
    """Serialize navigation metadata into JSON-ready entries."""
    return [
        {
            "id": identifier,
            "title": nav.title,
            "category": nav.category,
            "order": nav.order,
        }
        for identifier, nav in sorted(
            metadata.items(),
            key=lambda item: (item[1].order, item[0]),
        )
    ]


def load_navigation_metadata_from_path(path: Path) -> dict[str, NavigationMetadata]:
    """Parse navigation metadata from a sidebar config file."""
    return parse_navigation_config(path.read_text(encoding="utf-8"))


def load_bundled_navigation_metadata() -> dict[str, NavigationMetadata]:
    """Load the navigation metadata bundled with the generator."""
    entries = json.loads(BUNDLED_DOCS_NAVIGATION_PATH.read_text(encoding="utf-8"))
    return navigation_metadata_from_entries(entries)


def write_bundled_navigation_metadata(
    metadata: dict[str, NavigationMetadata],
) -> None:
    """Store navigation metadata as the generator's bundled JSON."""
    BUNDLED_DOCS_NAVIGATION_PATH.write_text(
        f"{json.dumps(navigation_metadata_entries(metadata), indent=2)}\n",
        encoding="utf-8",
    )


def load_navigation_metadata() -> dict[str, NavigationMetadata]:
    """Load navigation metadata from `MERMAID_DOCS_NAVIGATION`, else the bundled copy."""
    configured = os.environ.get("MERMAID_DOCS_NAVIGATION")

    if configured:
        configured_path = plugin_relative_path(configured)
        if not configured_path.exists():
            raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), str(configured_path))
        return load_navigation_metadata_from_path(configured_path)

    if BUNDLED_DOCS_NAVIGATION_PATH.exists():
        return load_bundled_navigation_metadata()

    if DEFAULT_DOCS_NAVIGATION_PATH.exists():
        return load_navigation_metadata_from_path(DEFAULT_DOCS_NAVIGATION_PATH)

    return {}


def extract_diagram_metadata(
    file: str,
    navigation_metadata: dict[str, NavigationMetadata] | None = None,
) -> DiagramMetadata:
    """Describe one syntax reference file for the diagram table."""
    navigation_metadata = navigation_metadata or {}
    identifier = re.sub(r"\.md$", "", file)
    text = (REFERENCES_DIR / file).read_text(encoding="utf-8")
    nav = navigation_metadata.get(identifier)

    return DiagramMetadata(
        id=identifier,
        file=file,
        title=normalize_markdown_text(
            nav.title if nav else first_heading(text) or title_from_id(identifier),
            escape_table_pipes=True,
        ),
        use_cases=first_useful_paragraph(text),
        category=normalize_markdown_text(
            nav.category if nav else "Diagram Syntax",
            escape_table_pipes=True,
        ),
        order=nav.order if nav else MAX_SAFE_INTEGER,
    )


def syntax_reference_files(
    navigation_metadata: dict[str, NavigationMetadata] | None = None,
) -> list[str]:
    """List the syntax reference files in sidebar order."""
    navigation_metadata = navigation_metadata or {}
    files = [
        path.name
        for path in REFERENCES_DIR.iterdir()
        if path.suffix == ".md" and not path.name.startswith("config-") and path.name != "examples.md"
    ]

    return sorted(
        files,
        key=lambda file: (
            navigation_metadata.get(
                file.removesuffix(".md"),
                NavigationMetadata("", MAX_SAFE_INTEGER, ""),
            ).order,
            file.lower(),
            file,
        ),
    )


def strip_generated_headers() -> None:
    """Remove the generated-file header from every bundled reference."""
    for path in REFERENCES_DIR.iterdir():
        if path.suffix != ".md":
            continue
        text = path.read_text(encoding="utf-8")
        stripped = GENERATED_HEADER_PATTERN.sub("", text, count=1)
        if stripped != text:
            path.write_text(stripped, encoding="utf-8")


def read_template(path: Path) -> str:
    """Read a generator template as text."""
    return path.read_text(encoding="utf-8")


def render_skill(diagrams: list[DiagramMetadata]) -> str:
    """Render the mermaid `SKILL.md` with its diagram table."""
    table = "\n".join(
        [
            "| Type | Documentation | Use Cases |",
            "| ---- | ------------- | --------- |",
            *[
                f"| {diagram.title} | [{diagram.file}](references/{diagram.file}) | {diagram.use_cases} |"
                for diagram in diagrams
            ],
        ]
    )

    diagram_count = len(diagrams)
    extra_count = max(diagram_count - 5, 0)

    return read_template(MERMAID_SKILL_TEMPLATE_PATH).format(
        diagram_count=diagram_count,
        extra_count=extra_count,
        diagram_table=table,
    )


def existing_sync_status() -> str | None:
    """Return the sync status line recorded in the plugin README, or None."""
    if not README_PATH.exists():
        return None
    match = SYNC_STATUS_PATTERN.search(README_PATH.read_text(encoding="utf-8"))
    return match.group("status").strip() if match else None


def sync_status(fallback_status: str | None) -> str:
    """Build the sync status line from the sync environment, else keep the recorded one."""
    if (
        os.environ.get("MERMAID_SYNC_SOURCE")
        or os.environ.get("MERMAID_SOURCE_COMMIT")
        or os.environ.get("MERMAID_SYNC_DATE")
    ):
        source = os.environ.get("MERMAID_SYNC_SOURCE", "local references")
        commit = os.environ.get("MERMAID_SOURCE_COMMIT", "unknown")
        date = os.environ.get("MERMAID_SYNC_DATE", js_iso_timestamp())
        return f"Last synced from Mermaid: {source} @ {commit} on {date}"

    return fallback_status or (f"Last synced from Mermaid: local references @ unknown on {js_iso_timestamp()}")


def sync_metadata(sync_status_line: str) -> SyncMetadata:
    """Parse a sync status line into its source, commit and date."""
    match = re.match(
        r"^Last synced from Mermaid: (.+) @ ([^\s]+) on (.+)$",
        sync_status_line,
    )
    return SyncMetadata(
        source=match.group(1) if match else "local references",
        commit=match.group(2) if match else "unknown",
        date=match.group(3) if match else "unknown",
    )


def render_third_party_notices(sync_status_line: str) -> str:
    """Render the Mermaid third-party notices for the recorded sync."""
    metadata = sync_metadata(sync_status_line)
    return f"""# Third-Party Notices

## Mermaid documentation

The Markdown files in `skills/mermaid/references` are synced from the
`{metadata.source}` repository.

- Source: https://github.com/mermaid-js/mermaid
- Synced commit: `{metadata.commit}`
- Synced date: {metadata.date}
- License: MIT

The generated warning banners from the upstream documentation build are removed
from the bundled reference files so the skill can use the documentation directly.
"""


def render_readme(diagrams: list[DiagramMetadata], sync_status_line: str) -> str:
    """Render the plugin README with diagrams grouped by category."""
    by_category: dict[str, list[str]] = {}
    for diagram in diagrams:
        by_category.setdefault(diagram.category, []).append(f"{diagram.title} (`{diagram.file}`)")

    supported_rows = "\n".join(
        f"| {category} | {', '.join(diagrams_in_category)} |" for category, diagrams_in_category in by_category.items()
    )

    return read_template(README_TEMPLATE_PATH).format(
        diagram_count=len(diagrams),
        supported_rows=supported_rows,
        sync_status_line=sync_status_line,
    )


def update_generated_docs() -> None:
    """Regenerate the skill, README, notices and reference headers in place."""
    fallback_sync_status = existing_sync_status()
    strip_generated_headers()
    navigation_metadata = load_navigation_metadata()
    files = syntax_reference_files(navigation_metadata)
    diagrams = [extract_diagram_metadata(file, navigation_metadata) for file in files]
    sync_status_line = sync_status(fallback_sync_status)
    MERMAID_SKILL_PATH.write_text(render_skill(diagrams), encoding="utf-8")
    README_PATH.write_text(render_readme(diagrams, sync_status_line), encoding="utf-8")
    THIRD_PARTY_NOTICES_PATH.write_text(
        render_third_party_notices(sync_status_line),
        encoding="utf-8",
    )


def main() -> int:
    """Regenerate the docs; return the process exit code."""
    update_generated_docs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
