# Changes here will be overwritten by Copier
_commit: v1.1.0
_src_path: gh:Alex-Kopylov/ai-ready-modern-python-template
author_name: Alex Kopylov
coverage_fail_under: 90
extra_linters:
- jscpd
- typos
- markdownlint
license: Skip
main_branch_name: main
parallel_testing: false
project_description: Simple, robust, and versatile marketplace for agent plugins, forged for the chaos of the AI world.
project_name: zweihander
python_version: '3.14'
use_github_actions: true
use_mutmut: true
