import json
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ROOT = REPO_ROOT / "plugins" / "mermaid-diagrams"


def read_text(relative_path: str) -> str:
    return (PLUGIN_ROOT / relative_path).read_text(encoding="utf-8")


def test_mermaid_plugin_uses_neutral_skill_layout() -> None:
    assert (PLUGIN_ROOT / "skills" / "mermaid" / "SKILL.md").is_file()
    assert (PLUGIN_ROOT / "skills" / "mermaid-lint" / "SKILL.md").is_file()
    assert not (PLUGIN_ROOT / ".claude" / "skills").exists()


def test_skill_files_avoid_claude_specific_source_packaging() -> None:
    combined = "\n".join(
        [
            read_text("skills/mermaid/SKILL.md"),
            read_text("skills/mermaid-lint/SKILL.md"),
            read_text("README.md"),
        ]
    )

    for phrase in ["Claude", ".claude/skills"]:
        assert phrase not in combined


def test_mermaid_lint_skill_is_renamed() -> None:
    lint_skill = read_text("skills/mermaid-lint/SKILL.md")

    assert "name: mermaid-lint" in lint_skill
    assert "name: lint-mermaid" not in lint_skill


def test_references_and_schema_are_preserved() -> None:
    references = sorted((PLUGIN_ROOT / "skills" / "mermaid" / "references").glob("*.md"))
    syntax_references = [
        path
        for path in references
        if not path.name.startswith("config-") and path.name != "examples.md"
    ]

    assert len(syntax_references) >= 30
    assert {
        "flowchart.md",
        "sequenceDiagram.md",
        "classDiagram.md",
        "entityRelationshipDiagram.md",
        "gantt.md",
    }.issubset({path.name for path in syntax_references})
    assert (
        PLUGIN_ROOT
        / "skills"
        / "mermaid-lint"
        / "references"
        / "linter_output_schema.json"
    ).is_file()

    for reference in references:
        first_lines = "\n".join(reference.read_text(encoding="utf-8").splitlines()[:6])
        assert "THIS IS AN AUTOGENERATED FILE" not in first_lines
        assert "DO NOT EDIT" not in first_lines


def test_linter_schema_reports_status_input_and_errors() -> None:
    schema = json.loads(
        (
            PLUGIN_ROOT
            / "skills"
            / "mermaid-lint"
            / "references"
            / "linter_output_schema.json"
        ).read_text(encoding="utf-8")
    )

    assert schema["type"] == "object"
    assert schema["required"] == ["status", "input", "errors"]
    assert sorted(schema["properties"]) == ["errors", "input", "status"]


def test_sync_scripts_are_plugin_scoped() -> None:
    script_text = "\n".join(
        [
            (PLUGIN_ROOT / "scripts" / "update-generated-docs.mjs").read_text(
                encoding="utf-8"
            ),
            (PLUGIN_ROOT / "scripts" / "sync-mermaid-docs.mjs").read_text(
                encoding="utf-8"
            ),
        ]
    )

    assert "skills/mermaid/references" in script_text
    assert "mermaid-lint" in script_text
    assert ".claude/skills" not in script_text
    assert "Claude" not in script_text
    assert "rootDir, 'README.md'" not in script_text


def test_sync_scripts_preflight_sources_and_preserve_sync_status() -> None:
    update_script = (PLUGIN_ROOT / "scripts" / "update-generated-docs.mjs").read_text(
        encoding="utf-8"
    )
    sync_script = (PLUGIN_ROOT / "scripts" / "sync-mermaid-docs.mjs").read_text(
        encoding="utf-8"
    )

    assert "existingSyncStatus" in update_script
    assert "MERMAID_DOCS_NAVIGATION" in update_script
    assert "Mermaid docs navigation file not found" in update_script
    assert "THIRD_PARTY_NOTICES.md" in update_script
    assert "renderThirdPartyNotices" in update_script
    assert "preflightSyncSource" in sync_script
    assert "existingSyncMetadata" in sync_script
    assert "existingSyncMetadata?.commit === sourceCommit" in sync_script


def test_sync_workflow_targets_mermaid_plugin_paths() -> None:
    workflow = (REPO_ROOT / ".github" / "workflows" / "sync-mermaid-docs.yml").read_text(
        encoding="utf-8"
    )

    assert "workflow_dispatch:" in workflow
    assert "pull_request:" in workflow
    assert "validate-generated-files:" in workflow
    assert "sync-docs:" in workflow
    assert "plugins/mermaid-diagrams/scripts/sync-mermaid-docs.mjs" in workflow
    assert "plugins/mermaid-diagrams/skills/** plugins/mermaid-diagrams/README.md" in workflow
    assert "node plugins/mermaid-diagrams/scripts/update-generated-docs.mjs" in workflow
    assert (
        "git diff --exit-code -- plugins/mermaid-diagrams/skills/mermaid/SKILL.md "
        "plugins/mermaid-diagrams/README.md "
        "plugins/mermaid-diagrams/THIRD_PARTY_NOTICES.md"
    ) in workflow
    assert "plugins/mermaid-diagrams/THIRD_PARTY_NOTICES.md" in workflow
    assert re.search(
        r"validate-generated-files:[\s\S]*?permissions:\n      contents: read",
        workflow,
    )
    assert re.search(
        r"sync-docs:\n    if: github\.event_name != 'pull_request'[\s\S]*?permissions:\n      contents: write",
        workflow,
    )
    assert "npm run" not in workflow


def test_plugin_manifests_point_to_neutral_skills() -> None:
    codex = json.loads(
        (PLUGIN_ROOT / ".codex-plugin" / "plugin.json").read_text(encoding="utf-8")
    )
    claude = json.loads(
        (PLUGIN_ROOT / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8")
    )

    assert codex["name"] == "mermaid-diagrams"
    assert claude["name"] == "mermaid-diagrams"
    assert codex["skills"] == "./skills/"
    assert claude["skills"] == "./skills/"
    assert codex["license"] == "MIT"


def test_marketplace_catalogs_include_mermaid_diagrams() -> None:
    codex_marketplace = json.loads(
        (REPO_ROOT / ".agents" / "plugins" / "marketplace.json").read_text(
            encoding="utf-8"
        )
    )
    claude_marketplace = json.loads(
        (REPO_ROOT / ".claude-plugin" / "marketplace.json").read_text(encoding="utf-8")
    )

    codex_entry = next(
        plugin
        for plugin in codex_marketplace["plugins"]
        if plugin["name"] == "mermaid-diagrams"
    )
    claude_entry = next(
        plugin
        for plugin in claude_marketplace["plugins"]
        if plugin["name"] == "mermaid-diagrams"
    )

    assert codex_entry["source"]["path"] == "./plugins/mermaid-diagrams"
    assert codex_entry["category"] == "Development"
    assert claude_entry["source"] == "./plugins/mermaid-diagrams"
    assert claude_entry["category"] == "development"


def test_readme_documents_plugin_without_runtime_lock_in() -> None:
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")

    assert "### `mermaid-diagrams`" in readme
    assert "`mermaid-lint`" in readme
    mermaid_section = readme.split("### `mermaid-diagrams`", 1)[1].split(
        "\n### `", 1
    )[0]
    assert "Claude" not in mermaid_section


def test_bundled_mermaid_references_have_provenance_notice() -> None:
    notice = (PLUGIN_ROOT / "THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")
    readme = (PLUGIN_ROOT / "README.md").read_text(encoding="utf-8")
    sync_match = re.search(r"Last synced from Mermaid: mermaid-js/mermaid @ ([0-9a-f]+) on ", readme)

    assert sync_match is not None

    assert "mermaid-js/mermaid" in notice
    assert sync_match.group(1) in notice
    assert "MIT" in notice
    assert "skills/mermaid/references" in notice
