import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ROOT = REPO_ROOT / "plugins" / "mermaid-diagrams"
TOOLING_ROOT = PLUGIN_ROOT / "plugin_maintenance"

sys.path.insert(0, str(PLUGIN_ROOT))

from plugin_maintenance.generated_docs import load_navigation_metadata


def read_text(relative_path: str) -> str:
    return (PLUGIN_ROOT / relative_path).read_text(encoding="utf-8")


def test_mermaid_plugin_uses_neutral_skill_layout() -> None:
    assert (PLUGIN_ROOT / "skills" / "mermaid" / "SKILL.md").is_file()
    assert (PLUGIN_ROOT / "skills" / "mermaid-lint" / "SKILL.md").is_file()
    assert not (PLUGIN_ROOT / ".claude" / "skills").exists()


def test_skill_files_avoid_claude_specific_source_packaging() -> None:
    combined = "\n".join(
        [
            read_text("skills/mermaid/SKILL.md"),
            read_text("skills/mermaid-lint/SKILL.md"),
            read_text("README.md"),
        ]
    )

    for phrase in ["Claude", ".claude/skills"]:
        assert phrase not in combined


def test_mermaid_lint_skill_is_renamed() -> None:
    lint_skill = read_text("skills/mermaid-lint/SKILL.md")

    assert "name: mermaid-lint" in lint_skill
    assert "name: lint-mermaid" not in lint_skill


def test_references_and_schema_are_preserved() -> None:
    references = sorted((PLUGIN_ROOT / "skills" / "mermaid" / "references").glob("*.md"))
    syntax_references = [
        path
        for path in references
        if not path.name.startswith("config-") and path.name != "examples.md"
    ]

    assert len(syntax_references) >= 30
    assert {
        "flowchart.md",
        "sequenceDiagram.md",
        "classDiagram.md",
        "entityRelationshipDiagram.md",
        "gantt.md",
    }.issubset({path.name for path in syntax_references})
    assert (
        PLUGIN_ROOT
        / "skills"
        / "mermaid-lint"
        / "references"
        / "linter_output_schema.json"
    ).is_file()

    for reference in references:
        first_lines = "\n".join(reference.read_text(encoding="utf-8").splitlines()[:6])
        assert "THIS IS AN AUTOGENERATED FILE" not in first_lines
        assert "DO NOT EDIT" not in first_lines


def test_bundled_navigation_metadata_is_used_without_source_checkout(monkeypatch) -> None:
    monkeypatch.delenv("MERMAID_DOCS_NAVIGATION", raising=False)
    metadata = load_navigation_metadata()

    assert (TOOLING_ROOT / "mermaid_navigation.json").is_file()
    assert metadata["flowchart"].title == "Flowchart"
    assert metadata["flowchart"].order == 0
    assert metadata["sequenceDiagram"].title == "Sequence Diagram"
    assert metadata["sequenceDiagram"].order == 1


def test_linter_schema_reports_status_input_and_errors() -> None:
    schema = json.loads(
        (
            PLUGIN_ROOT
            / "skills"
            / "mermaid-lint"
            / "references"
            / "linter_output_schema.json"
        ).read_text(encoding="utf-8")
    )

    assert schema["type"] == "object"
    assert schema["required"] == ["status", "input", "errors"]
    assert sorted(schema["properties"]) == ["errors", "input", "status"]


def test_python_tooling_is_plugin_scoped() -> None:
    generated_docs = read_text("plugin_maintenance/generated_docs.py")
    sync = read_text("plugin_maintenance/sync.py")
    template = read_text("plugin_maintenance/templates/mermaid_skill.md")

    assert (TOOLING_ROOT / "__init__.py").is_file()
    assert (TOOLING_ROOT / "generated_docs.py").is_file()
    assert (TOOLING_ROOT / "sync.py").is_file()
    assert (TOOLING_ROOT / "templates" / "mermaid_skill.md").is_file()
    assert (TOOLING_ROOT / "templates" / "readme.md").is_file()
    assert not (PLUGIN_ROOT / "scripts" / "update-generated-docs.mjs").exists()
    assert not (PLUGIN_ROOT / "scripts" / "sync-mermaid-docs.mjs").exists()

    combined = "\n".join([generated_docs, sync, template])
    assert "skills/mermaid/references" in combined
    assert ".claude/skills" not in combined
    assert "Claude" not in combined
    assert "User requirements: $ARGUMENTS" not in combined


def test_python_sync_preserves_first_port_safety_gates() -> None:
    generated_docs = read_text("plugin_maintenance/generated_docs.py")
    sync = read_text("plugin_maintenance/sync.py")

    assert "existing_sync_status" in generated_docs
    assert "MERMAID_DOCS_NAVIGATION" in generated_docs
    assert "mermaid_navigation.json" in generated_docs
    assert "Mermaid docs navigation file not found" in generated_docs
    assert "THIRD_PARTY_NOTICES.md" in generated_docs
    assert "render_third_party_notices" in generated_docs
    assert "preflight_sync_source" in sync
    assert "write_bundled_navigation_metadata" in sync
    assert "existing_sync_metadata" in sync
    assert "existing_sync_metadata.commit == source_commit" in sync


def test_sync_workflow_targets_mermaid_plugin_paths() -> None:
    workflow = (REPO_ROOT / ".github" / "workflows" / "sync-mermaid-docs.yml").read_text(
        encoding="utf-8"
    )

    assert "workflow_dispatch:" in workflow
    assert "pull_request:" in workflow
    assert "validate-generated-files:" in workflow
    assert "sync-docs:" in workflow
    assert "astral-sh/setup-uv" in workflow
    assert "uv run --project plugins/mermaid-diagrams" in workflow
    assert "python -m plugin_maintenance.generated_docs" in workflow
    assert "python -m plugin_maintenance.sync mermaid-source" in workflow
    assert "plugins/mermaid-diagrams/scripts/sync-mermaid-docs.mjs" not in workflow
    assert "node plugins/mermaid-diagrams/scripts/update-generated-docs.mjs" not in workflow
    assert "plugins/mermaid-diagrams/skills/** plugins/mermaid-diagrams/README.md" in workflow
    assert (
        "git diff --exit-code -- plugins/mermaid-diagrams/skills/mermaid/SKILL.md "
        "plugins/mermaid-diagrams/README.md "
        "plugins/mermaid-diagrams/THIRD_PARTY_NOTICES.md "
        "plugins/mermaid-diagrams/plugin_maintenance/mermaid_navigation.json"
    ) in workflow
    assert "plugins/mermaid-diagrams/THIRD_PARTY_NOTICES.md" in workflow
    assert "plugins/mermaid-diagrams/plugin_maintenance/mermaid_navigation.json" in workflow
    assert re.search(
        r"validate-generated-files:[\s\S]*?permissions:\n      contents: read",
        workflow,
    )
    assert re.search(
        r"sync-docs:\n    if: github\.event_name != 'pull_request'[\s\S]*?permissions:\n      contents: write",
        workflow,
    )
    assert "npm run" not in workflow


def test_plugin_python_project_declares_tooling_entrypoints() -> None:
    pyproject = read_text("pyproject.toml")

    assert 'name = "mermaid-diagrams"' in pyproject
    assert 'requires-python = ">=3.12"' in pyproject
    assert 'update-generated-docs = "plugin_maintenance.generated_docs:main"' in pyproject
    assert 'sync-mermaid-docs = "plugin_maintenance.sync:main"' in pyproject
    assert (PLUGIN_ROOT / "uv.lock").is_file()


def test_plugin_manifests_point_to_neutral_skills() -> None:
    codex = json.loads(
        (PLUGIN_ROOT / ".codex-plugin" / "plugin.json").read_text(encoding="utf-8")
    )
    claude = json.loads(
        (PLUGIN_ROOT / ".claude-plugin" / "plugin.json").read_text(encoding="utf-8")
    )

    assert codex["name"] == "mermaid-diagrams"
    assert claude["name"] == "mermaid-diagrams"
    assert codex["skills"] == "./skills/"
    assert claude["skills"] == "./skills/"
    assert codex["license"] == "MIT"


def test_marketplace_catalogs_include_mermaid_diagrams() -> None:
    codex_marketplace = json.loads(
        (REPO_ROOT / ".agents" / "plugins" / "marketplace.json").read_text(
            encoding="utf-8"
        )
    )
    claude_marketplace = json.loads(
        (REPO_ROOT / ".claude-plugin" / "marketplace.json").read_text(encoding="utf-8")
    )

    codex_entry = next(
        plugin
        for plugin in codex_marketplace["plugins"]
        if plugin["name"] == "mermaid-diagrams"
    )
    claude_entry = next(
        plugin
        for plugin in claude_marketplace["plugins"]
        if plugin["name"] == "mermaid-diagrams"
    )

    assert codex_entry["source"]["path"] == "./plugins/mermaid-diagrams"
    assert codex_entry["category"] == "Development"
    assert claude_entry["source"] == "./plugins/mermaid-diagrams"
    assert claude_entry["category"] == "development"


def test_readme_documents_plugin_without_runtime_lock_in() -> None:
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")

    assert "### `mermaid-diagrams`" in readme
    assert "`mermaid-lint`" in readme
    mermaid_section = readme.split("### `mermaid-diagrams`", 1)[1].split(
        "\n### `", 1
    )[0]
    assert "Claude" not in mermaid_section


def test_bundled_mermaid_references_have_provenance_notice() -> None:
    notice = (PLUGIN_ROOT / "THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")
    readme = (PLUGIN_ROOT / "README.md").read_text(encoding="utf-8")
    sync_match = re.search(r"Last synced from Mermaid: mermaid-js/mermaid @ ([0-9a-f]+) on ", readme)

    assert sync_match is not None

    assert "mermaid-js/mermaid" in notice
    assert sync_match.group(1) in notice
    assert "MIT" in notice
    assert "skills/mermaid/references" in notice
